---
- name: General test
  hosts: all
  tasks:
    - name: Write date as root to /tmp/_ANSIBLE_TEST
      become: true
      shell: "date > /tmp/_ANSIBLE_TEST"

- name: Put /etc under version control
  collections:
    ["debops.debops", "debops.roles01", "debops.roles02", "debops.roles03"]
  hosts: all
  become: true
  roles:
    - etckeeper

# Because there is/was an issue which could be workaround by rebooting once in a while
- name: Ensure nightly reboot
  hosts: all
  roles:
    - reboot-nightly

- name: Ensure utils
  hosts: all
  roles:
    - utils

# https://docs.bigbluebutton.org/2.4/install.html#pre-installation-checks
- name: Check host requirements
  # hosts: bbbservers
  hosts: all
  tasks:
    - name: Ensure language-pack-en is installed
      become: true
      apt:
        name: language-pack-en
      tags:
        - installation

    - name: Update locale
      become: true
      command: update-locale LANG=en_US.UTF-8
      tags:
        - configuration

    - name: Check that 'LANG=en_US.UTF-8' is in /etc/default/locale
      lineinfile:
        name: /etc/default/locale
        line: "LANG=en_US.UTF-8"
        # regexp: "LANG=.*en_US.UTF-8" # Does not work instead of "line"; no idea why.
        state: present
      check_mode: true
      register: conf
      failed_when: (conf is changed) or (conf is failed)
      changed_when: False # Never report that this task has changed anything
      tags:
        - check

    - name: Check that 'LC_ALL' is not in /etc/default/locale
      lineinfile:
        name: /etc/default/locale
        line: "LC_ALL"
        state: absent
      check_mode: true
      register: conf
      failed_when: (conf is changed) or (conf is failed)
      changed_when: False
      tags:
        - check

    - name: Set 'LANG=en_US.UTF-8' for systemd environment
      become: true
      shell: systemctl set-environment LANG=en_US.UTF-8
      tags:
        - configuration

    - name: Check 'en_US.UTF-8' is in systemd environment
      shell: systemctl show-environment | grep LANG=en_US.UTF-8
      ignore_errors: false
      changed_when: False
      tags:
        - check

    - name: Check distribution is Ubuntu 18.04 (bionic)
      shell: cat /etc/lsb-release | grep {{ item }}
      with_items:
        - DISTRIB_ID=Ubuntu
        - DISTRIB_RELEASE=18.04
        - DISTRIB_CODENAME=bionic
      ignore_errors: false
      changed_when: False
      tags:
        - check

    - name: Check architecture is 64 bit
      shell: uname -m | grep x86_64
      ignore_errors: false
      changed_when: False
      tags:
        - check

    - name: Check IPv6 is enabled
      shell: ip addr | grep inet6
      ignore_errors: false
      changed_when: False
      tags:
        - check

    - name: Check kernel is 4.x
      shell: uname -r | grep 4\.
      ignore_errors: false
      changed_when: False
      tags:
        - check

- name: Install BigBlueButton
  # hosts: bbbservers
  hosts: all
  become: true
  roles:
    - bigbluebutton

- name: Ensure additional BigBlueButton utils
  # hosts: bbbservers
  hosts: all
  become: true
  roles:
    - bigbluebutton-customizations
    - bigbluebutton-migration
    - fonts
