---
# TODO: Not sure this always works; e.g.:
#   debug1: connect to address 168.119.44.223 port 22: Connection timed out
#   debug1: connect to address 2a01:4f8:e0:189f::7 port 22: Network is unreachable
- name: Waiting for host to be available...
  hosts: root_server
  become: true
  gather_facts: false
  pre_tasks:
    - name: Waiting for host to be available...
      ansible.builtin.setup:
      register: setup_status
      until: setup_status is success
      delay: 10
      retries: 30

# TODO: Could be a role
- name: Waiting for cloud-init to finish...
  hosts: root_server
  tasks:
    - name: Waiting for cloud-init to finish...
      ansible.builtin.command: cloud-init status
      register: cloud_init_status
      retries: 30
      delay: 10
      until: "'done' in cloud_init_status.stdout or 'disabled' in cloud_init_status.stdout"
      changed_when: false
      check_mode: false  # Run this even in --check mode. In --check mode, this task would just fail otherwise.

# TODO: Could be a role
# TODO: Append datetime into a file instead.
- name: Leave a mark
  hosts: helloworld
  tasks:
    - name: Ensure file /tmp/_ANSIBLE_TEST
      ansible.builtin.file:
        path: /tmp/_ANSIBLE_TEST
        state: touch
        mode: "0666"
      changed_when: false # Pretend it did not change anything so it does not pollute the summary.
    - name: Write datetime to /tmp/_ANSIBLE_TEST_DATETIME
      ansible.builtin.shell: "date > /tmp/_ANSIBLE_TEST_DATETIME"
      changed_when: false # Pretend it did not change anything so it does not pollute the summary.
  tags:
    - always # Always run our silly little marker task :)

- name: Ensure apt cache is up-to-date
  hosts: root_server
  become: true
  tasks:
    - name: Ensure apt cache is up-to-date
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
  tags:
    - always # Always update apt cache, because it's annoying if an installation fails just because the cache is out-of-date.

- name: Ensure etckeeper
  hosts: root_server
  become: true
  roles:
    - debops.debops.etckeeper
  tags:
    - base
    - base:etckeeper
