---
- name: General test
  hosts: all
  tasks:
    - name: Write date as root to /tmp/_ANSIBLE_TEST
      become: true
      shell: "date > /tmp/_ANSIBLE_TEST"

- name: Ensure system configuration
  collections:
    ["debops.debops", "debops.roles01", "debops.roles02", "debops.roles03"]
  hosts: all
  become: true
  roles:
    - etckeeper
    # Because there is/was an issue which could be workaround by rebooting once in a while
    - reboot-nightly
    - utils

- name: Ensure BigBlueButton
  # hosts: bbbservers
  hosts: all
  become: true
  roles:
    - bigbluebutton
    - bigbluebutton-customizations
    - bigbluebutton-migration
    - fonts

# CAVEAT: After bbb, because it depends on its nginx configuration
- name: Ensure monitoring
  hosts: all
  become: true
  roles:
    - bigbluebutton-exporter
    - bigbluebutton-monitoring
    - node-exporter
