---
- name: General test
  hosts: all
  tasks:
    - name: Write date as root to /tmp/_ANSIBLE_TEST
      become: true
      shell: "date > /tmp/_ANSIBLE_TEST"

# https://docs.bigbluebutton.org/2.4/install.html#pre-installation-checks
- name: Check host requirements
  # hosts: bbbservers
  hosts: all
  tasks:
    - name: Ensure language-pack-en is installed
      become: true
      apt:
        name: language-pack-en

    - name: Update locale
      become: true
      command: update-locale LANG=en_US.UTF-8

    - name: Check that 'LANG=en_US.UTF-8' is in /etc/default/locale
      lineinfile:
        name: /etc/default/locale
        line: 'LANG=en_US.UTF-8'
        # regexp: "LANG=.*en_US.UTF-8" # Does not work instead of "line"; no idea why.
        state: present
      check_mode: true
      register: conf
      failed_when: (conf is changed) or (conf is failed)
      changed_when: False # Never report that this task has changed anything

    - name: Check that 'LC_ALL' is not in /etc/default/locale
      lineinfile:
        name: /etc/default/locale
        line: 'LC_ALL'
        state: absent
      check_mode: true
      register: conf
      failed_when: (conf is changed) or (conf is failed)
      changed_when: False

    - name: Set 'LANG=en_US.UTF-8' for systemd environment
      become: true
      shell: systemctl set-environment LANG=en_US.UTF-8

    - name: Check 'en_US.UTF-8' is in systemd environment
      shell: systemctl show-environment | grep LANG=en_US.UTF-8
      ignore_errors: false
      changed_when: False

    - name: Check distribution is Ubuntu 18.04 (bionic)
      shell: cat /etc/lsb-release | grep {{ item }}
      with_items:
        - DISTRIB_ID=Ubuntu
        - DISTRIB_RELEASE=18.04
        - DISTRIB_CODENAME=bionic
      ignore_errors: false
      changed_when: False

    - name: Check architecture is 64 bit
      shell: uname -m | grep x86_64
      ignore_errors: false
      changed_when: False

    - name: Check IPv6 is enabled
      shell: ip addr | grep inet6
      ignore_errors: false
      changed_when: False

    - name: Check kernel is 4.x
      shell: uname -r | grep 4\.
      ignore_errors: false
      changed_when: False

- name: Prepare host
  hosts: all
  tasks:
     - name: Install etckeeper
       become: true
       apt:
         name: etckeeper

     - name: Install tools
       become: true
       apt:
         pkg:
          - tmux
          - htop
          - mc
          - net-tools
          - nano
          - ncdu
          - nmap
          - iotop
          - wget
          - curl
          - iftop
          - pv
          - renameutils
          - netcat
          - locate
          - aptitude
          - reptyr

- name: Install BigBlueButton
  # hosts: bbbservers
  hosts: all
  tasks:
    - name: Create /_deployment/installation/
      become: true
      file:
        path: /_deployment/installation/
        state: directory

    - name: Download bbb-install.sh
      become: true
      get_url:
        url: https://ubuntu.bigbluebutton.org/bbb-install.sh
        dest: /_deployment/installation/
        force: true # Always download and update the file
        mode: '0770'

    - name: Disable memory check in bbb-install.sh
      become: true
      lineinfile:
        path: /_deployment/installation/bbb-install.sh
        regexp: '^  check_mem$'
        state: absent

    - name: Run bbb-install.sh
      become: true
      shell: "/_deployment/installation/bbb-install.sh -s -- -w -v {{ bbb_version }} -s `hostname -f` -e {{ letsencrypt_email }} -g"
      vars:
        bbb_version: bionic-24 # Hard-code it for now.
        letsencrypt_email: test@example.com
