---
- name: Leave a mark
  hosts: all
  tasks:
    - name: Ensure file /tmp/_ANSIBLE_TEST
      ansible.builtin.file:
        path: /tmp/_ANSIBLE_TEST
        state: file
    - name: Write datetime to /tmp/_ANSIBLE_TEST_DATETIME
      shell: "date > /tmp/_ANSIBLE_TEST_DATETIME"

# - name: Ensure system configuration
#   collections:
#     ["debops.debops", "debops.roles01", "debops.roles02", "debops.roles03"]
#   hosts: all
#   become: true
#   roles:
#     - etckeeper
#     - utils
