---
collections:
  - name: debops.debops
    version: 3.2.4
  - name: community.docker
    version: 4.4.0
  - name: community.general
    version: 10.4.0

roles:
  - name: roots.mailpit
    version: v1.0.0
