- name: Get BigBlueButton API secret
  shell: "bbb-conf --secret | grep 'Secret: ' | sed 's/^ *Secret:\\s//g'"
  register: bigbluebutton_api_secret
  changed_when: false

- name: Get BigBlueButton API URL
  shell: "bbb-conf --secret | grep 'URL: ' | sed 's/^ *URL:\\s//g'"
  register: bigbluebutton_api_url
  changed_when: false

- name: Ensure /_deployment/bigbluebutton-exporter
  file:
    path: /_deployment/bigbluebutton-exporter
    state: directory

- name: Ensure docker-compose.yaml
  template:
    src: docker-compose.yaml
    dest: /_deployment/bigbluebutton-exporter/docker-compose.yaml

# TODO: community.docker seems to have some ridiculous dependencies to be installed
# - name: Ensure service running
#   community.docker.docker_compose:
#     project_src: /_deployment/bigbluebutton-exporter/

- name: Ensure docker-compose
  become: true
  apt:
    name: docker-compose
  tags:
    - installation

- name: Ensure service running
  shell: "cd /_deployment/bigbluebutton-exporter/ && docker-compose up -d"
