- name: Check distribution is Ubuntu 18.04 (bionic)
  shell: cat /etc/lsb-release | grep {{ item }}
  with_items:
    - DISTRIB_ID=Ubuntu
    - DISTRIB_RELEASE=18.04
    - DISTRIB_CODENAME=bionic
  ignore_errors: false
  changed_when: false
  tags:
    - check

- name: Check architecture is 64 bit
  shell: uname -m | grep x86_64
  ignore_errors: false
  changed_when: false
  tags:
    - check

- name: Check IPv6 is enabled
  shell: ip addr | grep inet6
  ignore_errors: false
  changed_when: false
  tags:
    - check

- name: Check kernel is 4.x
  shell: uname -r | grep 4\.
  ignore_errors: false
  changed_when: false
  tags:
    - check
