---
- name: Install monitoring tools
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600  # Do not update if already done in the last hour.
    pkg:
      - htop
      - ncdu
      - iftop
      - iotop
      - dstat
      - nmon
      - multitail
      - pydf
  tags:
    - installation

- name: Install network tools
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600  # Do not update if already done in the last hour.
    pkg:
      - net-tools
      - wget
      - curl
      - aria2
      - netcat
      - nmap
      - ntpdate
      - mtr
      - mosh
      - dnsutils
      - apt-transport-https
  tags:
    - installation

- name: Install security tools
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600  # Do not update if already done in the last hour.
    pkg:
      - chkrootkit
  tags:
    - installation

- name: Install compression tools
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600  # Do not update if already done in the last hour.
    pkg:
      - zip
      - pigz  # parallel gz
      - pbzip2  # parallel bz2
      - p7zip-full
      - xz-utils
      - zstd
      # - dtrx  # Not available on Ubuntu 20.04 (focal)
  tags:
    - installation

- name: Install misc tools
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600  # Do not update if already done in the last hour.
    pkg:
      - nano
      - mc
      - tmux
      # - screen
      - pv
      - renameutils
      - locate
      - aptitude
      - reptyr
      - secure-delete
      - git
  tags:
    - installation