- name: Install tools
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600 # Do not update if already done in the last hour.
    pkg:
      - tmux
      - htop
      - mc
      - net-tools
      - nano
      - ncdu
      - nmap
      - iotop
      - wget
      - curl
      - iftop
      - pv
      - renameutils
      - netcat
      - locate
      - aptitude
      - reptyr
  tags:
    - installation
