- name: Get BigBlueButton API secret
  shell: "bbb-conf --secret | grep 'Secret: ' | sed 's/^ *Secret:\\s//g'"
  register: bigbluebutton_secret
  changed_when: false

- name: Get BigBlueButton API URL
  shell: "bbb-conf --secret | grep 'URL: ' | sed 's/^ *URL:\\s//g'"
  register: bigbluebutton_url
  changed_when: false

- name: Ensure /_deployment/bigbluebutton-monitoring
  file:
    path: /_deployment/bigbluebutton-monitoring
    state: directory

- name: Ensure docker-compose.yaml
  template:
    src: docker-compose.yaml
    dest: /_deployment/bigbluebutton-monitoring/docker-compose.yaml

- name: Ensure docker-compose
  become: true
  apt:
    name: docker-compose
  tags:
    - installation

- name: Ensure service running
  shell: "cd /_deployment/bigbluebutton-monitoring/ && docker-compose up -d"
