# Needed for htpasswd role
- name: Ensure python passlib
  become: true
  apt:
    pkg:
      - python-passlib
      - python3-passlib
  tags:
    - installation

- name: Ensure Basic Auth
  htpasswd:
    path: /etc/nginx/conf.d/bigbluebutton-monitoring.htpasswd
    name: "{{ bigbluebutton_monitoring_proxy_basic_auth_username }}"
    password: "{{ bigbluebutton_monitoring_proxy_basic_auth_password }}"

- name: Ensure nginx config
  template:
    src: nginx.conf
    dest: /etc/bigbluebutton/nginx/bigbluebutton-monitoring.nginx
