= Tags
ifndef::relative_imagesdir[]
:relative_imagesdir: .
endif::[]
:toc:

This file describes the tags used in the playbook.
Tags are used to only run a certain subset of the playbook, e.g.
if you want to only update the backup stuff: `+ansible-playbook [...] --tags backup playbook.yaml+` For multiple tags, use `--tags backup,unicorns`.

To get the whole list of (also undocumented) tags, run `ansible-playbok -i inventory.yaml --list-tags playbook.yaml`.

Use `+ansible-playbook [...] --tags backup --list-tasks playbook.yaml+` to list which tasks would run.
Use `+ansible-playbook [...] --ask-vault-pass --check --tags backup playbook.yaml+` for a dry-run to check which tasks on which hosts would actually run and would probably change something.

* `base` ensures all the basic `base:*` stuff.
* `base:etckeeper` ensures etckeeper.
* `base:utils` ensures utilities are installed.
* `base:reboot-nightly` ensures the host reboot every night.
* `backup` ensures the backup.
It especially ensures the borgmatic setup.
TODO: Not sure if this should also just be in the `base:*` tag hierarchy.
* `services` installs the actual `services:*` services.
These might be rather slow tasks.
* `monitoring` ensures all `monitoring:*`.
* `monitoring:prometheus` ensures all `monitoring:prometheus:*`.
* `monitoring:prometheus:node` ensures the Prometheus `node-exporter`.
* `monitoring:prometheus:misc` ensures the Prometheus `misc-exporter`.
* `monitoring:prometheus:systemd` ensures the Prometheus `systemd-exporter`.

== Tips and Workarounds

* `verify` checks if services are actually working (e.g. respond on port, certain text in response).
* `slow` contains very slow tasks (which would run always, because they are just a large script).
You can skip them with `--skip-tags slow` if they had already run once.

== Development

NOTE: `import_*` will inherit a tag;
`include_*` will not (see `apply`: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html#tag-inheritance-for-includes-blocks-and-the-apply-keyword).
