- name: Ensure /_deployment/
  file:
    path: /_deployment/
    state: directory

# TODO: just checking out the official repo does not fit very well with company-internal branches
- name: Checkout bigbluebutton-migration
  git:
    #repo: git@github.com:debuglevel/bigbluebutton-migration.git
    repo: https://github.com/debuglevel/bigbluebutton-migration.git
    dest: /_deployment/bigbluebutton-migration
