- name: Ensure /_deployment/
  file:
    path: /_deployment/
    state: directory

# # NOTE: Just checking out the official repository does not fit very well with company-internal branches (or even git servers which are only available from the Ansible controller but not the host)
# - name: Checkout bigbluebutton-migration
#   git:
#     #repo: git@github.com:debuglevel/bigbluebutton-migration.git
#     repo: https://github.com/debuglevel/bigbluebutton-migration.git
#     dest: /_deployment/bigbluebutton-migration
#   tags:
#     - bigbluebutton-migration
    
# Use a local git submodule which is copied, as this circumvents problems with git servers which are not accesible from the host
- name: Copy directory to host
  copy:
    src: bigbluebutton-migration.git/
    dest: /_deployment/bigbluebutton-migration/
    mode: preserve
  tags:
    - bigbluebutton-migration

# # CAVEAT: Does not work with spaces in path
# - name: Synchronize
#   ansible.posix.synchronize:
#     src: bigbluebutton-migration.git/
#     dest: /_deployment/bigbluebutton-migration/
#   tags:
#     - bigbluebutton-migration
